#!/usr/bin/python

import sys
import subprocess
import json
import os

output = subprocess.check_output(["docker", "ps", "-notrunc"])
output = output.split("\n")
for line in output[1:]:
	cols = line.split("   ")
	if sys.argv[1] in cols[1]:
		print "attaching to %s %s" % (cols[0], cols[1])
		os.execlp("lxc-attach", "lxc-attach", "-n", cols[0])
