#!/usr/bin/python

import sys
import subprocess
import json
import os
import re

image_re = re.compile("(.+?)/(.+?):(.+)")

hosts = []
output = subprocess.check_output(["docker", "ps", "-notrunc"])
output = output.split("\n")
for line in output[1:]:
	cols = line.split("   ")

	if len(cols) > 1 and len(cols[0]) > 0 and len(cols[1]) > 0:
		ip = subprocess.check_output(["doip", cols[0]]).rstrip()
		match = image_re.match(cols[1])
		if match:
			repo, image, tag = match.groups()
			hosts.append("%s\t\t%s.docker.giantmonkey.de\t\t%s.g.giantmonkey.de\t\t%s" % (ip, image, image, image))  

old = open("/etc/hosts").read()
old_hosts = re.findall(r"# DOCKER START.*# DOCKER END", old, re.MULTILINE | re.DOTALL)[0] 
new_hosts = "# DOCKER START\n" + "\n".join(hosts) + "\n# DOCKER END"
new = old.replace(old_hosts, new_hosts);

file = open("/etc/hosts", "w")
file.write(new)
file.close()

print "Replaced containers in /etc/hosts:"
print new_hosts
