#!/usr/bin/python

import sys
import subprocess
import json

output = subprocess.check_output(["docker", "inspect", sys.argv[1]])
info = json.loads(output)

if len(info) == 0:
	print >> sys.stderr, "Searching for container by name..."
	output = subprocess.check_output(["docker", "ps", "-notrunc"])
	output = output.split("\n")
	for line in output[1:]:  
		cols = line.split("   ")
		if len(cols) > 1 and sys.argv[1] in cols[1]:
			output = subprocess.check_output(["docker", "inspect", cols[0]])
			info = json.loads(output)

print info[0]["ID"]
