#!/usr/bin/python

import sys
import subprocess
import os
import re

parents = []
parent = sys.argv[1]

while parent:
	# stop if we have found a base image
	if "/" not in parent:
		break

	parents.append(parent)
        # TODO: assume unprefixed directorynames. maybe remove this
	directory = parent.split("/")[1]
	dockerfile = open(os.path.join(directory, "Dockerfile"))
	match = re.search(r"^FROM\s+(.+)", dockerfile.read())
	if match:
		parent = match.group(1)
	else:
		parent = None

parents.reverse()

for parent in parents:
	# TODO: assume unprefixed directorynames. maybe remove this
	directory = parent.split("/")[1]
	print "building image", parent, "..."
	subprocess.check_call(["docker", "build", "-t", parent, directory]) 

