#!/usr/bin/python

import argparse
import subprocess

def parse_arguments():
        parser = argparse.ArgumentParser()
        parser.add_argument("--container", type=str, default="varnish", help="id or name of varnish container")

        return parser.parse_args()


def reload_varnish(args):
	subprocess.check_call("echo \"/usr/share/varnish/reload-vcl\" | dt-attach %s" % args.container, shell=True)
	print "Reloaded varnish config"

args = parse_arguments()
reload_varnish(args)

